id: IAC69FD8D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T21:07:20+00:00'
last_modified: '2022-06-08T04:03:18.539614+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG13759
  title: གསུང་འབུམ། གྲགས་པ་བཤད་སྒྲུབ། ༼གློག་ཀླད་པར་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    11FF:
      image_group_id: I1KG15427
      title: Volume 1 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      total_pages: 480
      order: 1
      base_file: 11FF.txt
    BAFD:
      image_group_id: I1KG15428
      title: Volume 2 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      total_pages: 416
      order: 2
      base_file: BAFD.txt
    9BDD:
      image_group_id: I1KG15429
      title: Volume 3 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      total_pages: 352
      order: 3
      base_file: 9BDD.txt
    5E25:
      image_group_id: I1KG15430
      title: Volume 4 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      total_pages: 452
      order: 4
      base_file: 5E25.txt
    48B6:
      image_group_id: I1KG15431
      title: Volume 5 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      total_pages: 464
      order: 5
      base_file: 48B6.txt
    A0AD:
      image_group_id: I1KG15432
      title: Volume 6 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      total_pages: 380
      order: 6
      base_file: A0AD.txt
    8E81:
      image_group_id: I1KG15433
      title: Volume 7 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      total_pages: 439
      order: 7
      base_file: 8E81.txt
    B1C6:
      image_group_id: I1KG15434
      title: Volume 8 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      total_pages: 460
      order: 8
      base_file: B1C6.txt
    BF1B:
      image_group_id: I1KG15435
      title: Volume 9 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      total_pages: 444
      order: 9
      base_file: BF1B.txt
    A5FD:
      image_group_id: I1KG15436
      title: Volume 10 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      total_pages: 524
      order: 10
      base_file: A5FD.txt
    D699:
      image_group_id: I1KG15437
      title: Volume 11 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      total_pages: 380
      order: 11
      base_file: D699.txt
    4A4A:
      image_group_id: I1KG15438
      title: Volume 12 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      total_pages: 374
      order: 12
      base_file: 4A4A.txt
    0EBB:
      image_group_id: I1KG15439
      title: Volume 13 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      total_pages: 432
      order: 13
      base_file: 0EBB.txt
    1C22:
      image_group_id: I1KG15440
      title: Volume 14 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      total_pages: 432
      order: 14
      base_file: 1C22.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
